server:
  port: 8989
3clearServer:
  dev: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://182.42.127.16:5432/3clear_test?currentSchema=public
    platform: postgres


#mybatis 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    '*': debug



